---
- name: Set facts
  ansible.builtin.set_fact:
    checkmk_host_url: "{{ checkmk_agent_host_protocol | mandatory(true) }}://{{ checkmk_agent_host_hostname | mandatory(true) }}:{{ checkmk_host_port_web | mandatory(true) }}"
    checkmk_agent_registered_file:
      linux: /.checkmk-agent-registered
      windows: "{{ ansible_env['ProgramFiles(x86)'] }}\\checkmk\\.checkmk-agent-registered"
    checkmk_agent_hostname: >-
      {%- if 'checkmk_agent_hostname' in hostvars[inventory_hostname] -%}
      {{- hostvars[inventory_hostname]['checkmk_agent_hostname'] -}}
      {%- else -%}
      {{- inventory_hostname -}}
      {%- endif -%}

- name: Configure linux agent
  when: ansible_system | lower == 'linux'
  ansible.builtin.include_tasks: tasks/os-linux.yml

- name: Configure windows agent
  when: ansible_system | lower == 'windows'
  ansible.builtin.include_tasks: tasks/os-windows.yml

- name: Configure docker plugin
  when: checkmk_plugin_docker_enabled | bool
  ansible.builtin.include_tasks: tasks/plugin-docker.yml
