---
- name: Install checkmk agent
  become: true
  ansible.builtin.win_package:
    path: "{{ checkmk_host_url }}/{{ checkmk_site_id | mandatory(true) }}/check_mk/agents/{{ checkmk_agent_download_path | mandatory(true) }}"

- name: Check for .checkmk-agent-registered file
  ansible.builtin.win_stat:
    path: "{{ checkmk_agent_registered_file.windows }}"
  register: stat_agent_registered

- name: Register agent
  when: (not stat_agent_registered.stat.exists | bool) or (checkmk_agent_force_register | bool)
  block:
    - name: Register checkmk agent
      become: true
      ansible.builtin.win_shell:
          chdir: "{{ ansible_env['ProgramFiles(x86)'] }}\\checkmk\\service"
          cmd: >-
            ./cmk-agent-ctl.exe register \
              --hostname "{{ checkmk_agent_hostname | mandatory(true) }}" \
              --server "{{ checkmk_agent_host_hostname | mandatory(true) }}:{{ checkmk_host_port_agent}}" \
              --site "{{ checkmk_site_id | mandatory(true) }}" \
              --user "{{ checkmk_agent_registration_username | mandatory(true) }}" \
              --password "{{ checkmk_agent_registration_password | mandatory(true) }}" \
              --trust-cert

    - name: Ensure .checkmk-agent-configured file
      become: true
      ansible.builtin.win_file:
        path: "{{ checkmk_agent_registered_file.windows }}"
        state: touch
