---
- name: Ensure docker python package
  become: true
  ansible.builtin.pip:
    name:
      - docker

- name: Ensure docker plugin file
  become: true
  ansible.builtin.get_url:
    url: "{{ checkmk_host_url }}/cmk/check_mk/agents/plugins/mk_docker.py"
    dest: /usr/lib/check_mk_agent/plugins/mk_docker.py
    owner: root
    group: root
    mode: "755"

- name: Ensure docker plugin config file
  become: true
  ansible.builtin.copy:
    src: files/docker.cfg
    dest: /etc/check_mk/docker.cfg
    owner: root
    group: root
    mode: "644"
